version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - l3ala9ate

  worpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - l3ala9ate
      
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - worpress
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - l3ala9ate 
    
volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ouidriss/data
      o: bind
  wordpress_volume:
      driver: local
      driver_opts:
        type: none
        device: /home/ouidriss/data
        o: bind
networks:
  l3ala9ate:
    driver: bridge