version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - l3ala9ate
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - l3ala9ate
    restart: always
      
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - l3ala9ate
    restart: always
    
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    env_file:
      - .env
    networks:
      - l3ala9ate
    depends_on:
      - wordpress
    restart: always

  ftp-server:
    build: ./requirements/bonus/ftp-server
    container_name: ftp-server
    image: ftp-server
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/home/ftpuser/
    ports:
      - "21:21"
      - "20:20"
      - "1024-1048:1024-1048"
    networks:
      - l3ala9ate
    restart: always
    
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    env_file:
      - .env
    networks:
      - l3ala9ate
    depends_on:
      - nginx
    volumes:
      - wordpress_volume:/var/www/html/
    restart: always

  portainer :
    build: ./requirements/bonus/portainer
    container_name: portainer
    image: portainer
    env_file:
      - .env
    networks:
      - l3ala9ate
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ouidriss/data/mariadb
      o: bind
  wordpress_volume:
      driver: local
      driver_opts:
        type: none
        device: /home/ouidriss/data/wordpress
        o: bind
networks:
  l3ala9ate:
    driver: bridge