# Start from a Debian image.
FROM debian:bullseye

RUN apt update && apt install -y wget tar

RUN wget https://github.com/portainer/portainer/releases/download/1.10.1/portainer-1.10.1-linux-amd64.tar.gz

RUN tar -xpf portainer-1.10.1-linux-amd64.tar.gz

WORKDIR /portainer

RUN chmod +x portainer

EXPOSE 9443

CMD ["./portainer"]