FROM debian:bullseye

RUN apt-get update && apt-get install -y nginx \
    && apt install openssl -y 

RUN mkdir -p /etc/nginx/ssl
COPY tools/nginx.conf /etc/nginx/nginx.conf
COPY tools/nginx.sh /

RUN chmod +x /nginx.sh

EXPOSE 443

CMD ["./nginx.sh" ]